apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: image-updater-application  
  namespace: argocd
  annotations:
    argocd-image-updater.argoproj.io/image-list: myalias=docker.io/kishoredurai/kishore-nginx
    argocd-image-updater.argoproj.io/myalias.update-strategy: latest  #Write repository name
    argocd-image-updater.argoproj.io/write-back-method: git          #Setting git credential
    argocd-image-updater.argoproj.io/git-branch: image-updater                                          #git branch where your workflow exists
    argocd-image-updater.argoproj.io/myalias.force-update: "true"

spec:
  project: default

  source:
    repoURL: https://github.com/kishoredurai/argocd-poc.git
    targetRevision: image-updater  
    path: argocd-image-updater/dev # path of the kubernetes application code means where you stored deployment.yaml, service.yaml etc

    
  destination:
    server: https://kubernetes.default.svc  # if you want to deploy application in the same cluster where argocd server is running if thats diffrent then use cluster IP address.
    namespace: myapp

  syncPolicy:
    syncOptions:
    - CreateNamespace=true
    automated:
      selfHeal: true
      prune: true